# Generated by Django 4.1.2 on 2022-10-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_first_name',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_last_name',
            field=models.CharField(default='', max_length=264),
        ),
    ]
