# Generated by Django 4.1.2 on 2022-10-29 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0004_rename_first_name_profile_f_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='l_name',
        ),
    ]
