# Generated by Django 4.1.2 on 2022-10-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0005_remove_profile_f_name_remove_profile_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=264),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=264),
        ),
    ]
