# Generated by Django 4.1.2 on 2022-10-29 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0006_profile_email_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default='No Country', max_length=50),
        ),
    ]
