# Generated by Django 4.1.2 on 2022-10-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0002_profile_user_first_name_profile_user_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_first_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_last_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=264),
        ),
    ]
