# Generated by Django 4.1.2 on 2022-10-29 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0007_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
