# Generated by Django 4.1.2 on 2022-11-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0010_profile_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='category',
            new_name='news_category',
        ),
    ]
