# Generated by Django 4.1.2 on 2022-11-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0011_rename_category_profile_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='news_category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Sports', 'Sports')], max_length=20),
        ),
    ]
