# Generated by Django 4.1.2 on 2022-11-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hermes', '0012_alter_profile_news_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(choices=[('AU', 'Australia'), ('CA', 'Canada'), ('IN', 'India'), ('NZ', 'New Zealand'), ('JP', 'Japan'), ('GB', 'United Kingdom'), ('US', 'United States')], max_length=20),
        ),
    ]
